// flow-typed signature: 0c617a4690b89b0cb7dc2f8c85e23af2
// flow-typed version: <<STUB>>/eslint-config-ericmasiello_v^1.2.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-ericmasiello'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-ericmasiello' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-ericmasiello/configs/flow-typed.eslintrc' {
  declare module.exports: any;
}

declare module 'eslint-config-ericmasiello/flow' {
  declare module.exports: any;
}

declare module 'eslint-config-ericmasiello/jest' {
  declare module.exports: any;
}

declare module 'eslint-config-ericmasiello/mocha' {
  declare module.exports: any;
}

declare module 'eslint-config-ericmasiello/react-native' {
  declare module.exports: any;
}

declare module 'eslint-config-ericmasiello/react' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-ericmasiello/configs/flow-typed.eslintrc.js' {
  declare module.exports: $Exports<'eslint-config-ericmasiello/configs/flow-typed.eslintrc'>;
}
declare module 'eslint-config-ericmasiello/flow.js' {
  declare module.exports: $Exports<'eslint-config-ericmasiello/flow'>;
}
declare module 'eslint-config-ericmasiello/index' {
  declare module.exports: $Exports<'eslint-config-ericmasiello'>;
}
declare module 'eslint-config-ericmasiello/index.js' {
  declare module.exports: $Exports<'eslint-config-ericmasiello'>;
}
declare module 'eslint-config-ericmasiello/jest.js' {
  declare module.exports: $Exports<'eslint-config-ericmasiello/jest'>;
}
declare module 'eslint-config-ericmasiello/mocha.js' {
  declare module.exports: $Exports<'eslint-config-ericmasiello/mocha'>;
}
declare module 'eslint-config-ericmasiello/react-native.js' {
  declare module.exports: $Exports<'eslint-config-ericmasiello/react-native'>;
}
declare module 'eslint-config-ericmasiello/react.js' {
  declare module.exports: $Exports<'eslint-config-ericmasiello/react'>;
}
