// flow-typed signature: 029594465abb5a258afef222ff931937
// flow-typed version: <<STUB>>/isdev_v^1.0.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'isdev'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'isdev' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'isdev/tests/spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'isdev/index' {
  declare module.exports: $Exports<'isdev'>;
}
declare module 'isdev/index.js' {
  declare module.exports: $Exports<'isdev'>;
}
declare module 'isdev/tests/spec.js' {
  declare module.exports: $Exports<'isdev/tests/spec'>;
}
